# Generated by Django 4.1.1 on 2022-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0002_alter_singer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
